/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'

// Create Virtual Routes

const KnowledgeLazyImport = createFileRoute('/knowledge')()
const ChatIdLazyImport = createFileRoute('/chat/$id')()

// Create/Update Routes

const KnowledgeLazyRoute = KnowledgeLazyImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/knowledge.lazy').then((d) => d.Route))

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ChatIdLazyRoute = ChatIdLazyImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/chat.$id.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeLazyImport
      parentRoute: typeof rootRoute
    }
    '/chat/$id': {
      id: '/chat/$id'
      path: '/chat/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof ChatIdLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/knowledge': typeof KnowledgeLazyRoute
  '/chat/$id': typeof ChatIdLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/knowledge': typeof KnowledgeLazyRoute
  '/chat/$id': typeof ChatIdLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/knowledge': typeof KnowledgeLazyRoute
  '/chat/$id': typeof ChatIdLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/knowledge' | '/chat/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/knowledge' | '/chat/$id'
  id: '__root__' | '/' | '/knowledge' | '/chat/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KnowledgeLazyRoute: typeof KnowledgeLazyRoute
  ChatIdLazyRoute: typeof ChatIdLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KnowledgeLazyRoute: KnowledgeLazyRoute,
  ChatIdLazyRoute: ChatIdLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/knowledge",
        "/chat/$id"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/knowledge": {
      "filePath": "knowledge.lazy.tsx"
    },
    "/chat/$id": {
      "filePath": "chat.$id.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
